householdpower<-read.csv("household_power_consumption.txt",h=T,sep = ";",nrows=2075259,stringsAsFactors=FALSE)
str(householdpower)
head(householdpower)
householdpower1<-subset(householdpower,householdpower$Date =="1/2/2007")
str(householdpower1)
head(householdpower1)
householdpower1<-subset(householdpower,householdpower$Date == "1/2/2007" | householdpower$Date == "2/2/2007")
str(householdpower1)
householdpower1$Global_active_power<-as.numeric(householdpower1$Global_active_power)
png("plot1.png",width=480,height=480)
hist(householdpower1$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power(kilowatts)")
dev.off()
