householdpower<-read.csv("household_power_consumption.txt",h=T,sep = ";",nrows=2075259,stringsAsFactors=FALSE)
str(householdpower)
head(householdpower)
householdpower1<-subset(householdpower,householdpower$Date =="1/2/2007")
str(householdpower1)
head(householdpower1)
householdpower1<-subset(householdpower,householdpower$Date == "1/2/2007" | householdpower$Date == "2/2/2007")
str(householdpower1)
dates<-householdpower1$Date
head(dates)
datestime<-paste(dates,householdpower1$Time)
head(datestime)
time<-strptime(datestime,"%d/%m/%Y %H:%M:%S")
head(time)
plot(time,householdpower1$Global_active_power,typ='l',ylab="Global Active Power (kilowatts)", xlab="")
dev.copy(png,file="plot2.png")
dev.off()