householdpower<-read.csv("household_power_consumption.txt",h=T,sep = ";",nrows=2075259,stringsAsFactors=FALSE)
str(householdpower)
head(householdpower)
householdpower1<-subset(householdpower,householdpower$Date =="1/2/2007")
str(householdpower1)
head(householdpower1)
householdpower1<-subset(householdpower,householdpower$Date == "1/2/2007" | householdpower$Date == "2/2/2007")
str(householdpower1)
dates<-householdpower1$Date
head(dates)
datestime<-paste(dates,householdpower1$Time)
head(datestime)
time<-strptime(datestime,"%d/%m/%Y %H:%M:%S")
head(time)
householdpower1$Global_active_power<-as.numeric(householdpower1$Global_active_power)
householdpower1$Voltage<-as.numeric(householdpower1$Voltage)
householdpower1$Global_reactive_power<-as.numeric(householdpower1$Global_reactive_power)
householdpower1$Sub_metering_1<-as.numeric(householdpower1$Sub_metering_1)
householdpower1$Sub_metering_2<-as.numeric(householdpower1$Sub_metering_2)
png("plot4.png")
par(mfrow=c(2,2))
par(mar=c(4,4,2,2))
plot(time,householdpower1$Global_active_power,typ='l',ylab="Global Active Power", xlab="")
par(mar=c(4,4,2,2))
plot(time,householdpower1$Voltage,typ='l',ylab="Voltage",xlab="datetime")
par(mar=c(4,4,2,2))
plot(time,householdpower1$Sub_metering_1,typ='l',ylab="Energy sub metering",xlab="")
points(time,householdpower1$Sub_metering_2,type="l",lwd=1,col="red")
points(time,householdpower1$Sub_metering_3,type="l",lwd=1,col="blue")
legend("topright",lty=c(1,1,1),lwd=c(1,1,1),pch=NA,col=c("black","red","blue"),box.lwd=0,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
par(mar=c(4,4,2,2))
plot(time,householdpower1$Global_reactive_power,typ='l',lwd=2,ylab="Global_reactive_power",xlab="datetime")
dev.off()
