householdpower<-read.csv("household_power_consumption.txt",h=T,sep = ";",nrows=2075259,stringsAsFactors=FALSE)
str(householdpower)
head(householdpower)
householdpower1<-subset(householdpower,householdpower$Date =="1/2/2007")
str(householdpower1)
head(householdpower1)
householdpower1<-subset(householdpower,householdpower$Date == "1/2/2007" | householdpower$Date == "2/2/2007")
str(householdpower1)
dates<-householdpower1$Date
head(dates)
datestime<-paste(dates,householdpower1$Time)
head(datestime)
time<-strptime(datestime,"%d/%m/%Y %H:%M:%S")
head(time)
householdpower1$Sub_metering_1<-as.numeric(householdpower1$Sub_metering_1)
householdpower1$Sub_metering_2<-as.numeric(householdpower1$Sub_metering_2)
png("plot3.png",width=480,height=480)
plot(time,householdpower2$Sub_metering_1,typ='l',ylab="Energy sub metering",xlab="")
points(time,householdpower2$Sub_metering_2,type="l",lwd=1,col="red")
points(time,householdpower2$Sub_metering_3,type="l",lwd=1,col="blue")
legend("topright",lty=c(1,1,1),lwd=c(1,1,1),pch=NA,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()